### ISSUE TITLE
EndToEnd Identification shouldn't default to name

### ISSUE THREAD

**Issue by Lennix** [php-sepa-xml/php-sepa-xml#129] opened 2022-02-07 15:11 UTC
https://github.com/php-sepa-xml/php-sepa-xml/blob/fc8ae552c8a2015d07bb2c4f6a3121a0f9fa584b/src/TransferInformation/BaseTransferInformation.php#L109

I had some trouble uploading an 001.001.03 file and after a long debugging session I found out that the EndToEndId field cant be longer than 35 characters.
By default if no EndToEndId is provided the name is used, which can exceed 35 characters resulting in an invalid file.

The sepa standard defines that an empty EndToEndId should be set to "NOTPROVIDED".

I suggest following the standard in this case. Which is also a quick fix.

**Comment by BorislavSabev** [comment] 2024-02-06 15:07
@Lennix currently this library does not validate your inputs by design. It will only check their types. 
Thus this is regarded out of scope for this library. 

We are looking into having custom validators auto-generated from the ISO20022 XSDs but this is not implemented yet. 
The current advisory is that each project using this library should pre-validate their own data as per the standard. All standard documents are available over at: https://www.iso20022.org/

**Comment by Lennix** [comment] 2024-02-06 16:43
> The sepa standard defines that an empty EndToEndId should be set to "NOTPROVIDED".

I would just go with the standard. Otherwise even if I did my own validation, it would fail because setting EndToEndId to name is not according to standard and might fail.

**Comment by BorislavSabev** [comment] 2024-05-16 10:18
@Lennix as far as I can tell “NOTPROVIDED” is suggested in some documents as a kind of default value to fulfill the ISO syntax requirements. For example [here](https://www.swift.com/swift-resource/35336/download) in the pain.001.001.03 tab. However the standard itself does not mandate this as the default value.

If you can point me to the place where "NOTPROVIDED" is defined as the default I would consider it.


Don't get me wrong - I agree with your assumption in general but I am also trying to keep the library standards-compliant.

**Comment by BorislavSabev** [comment] 2024-07-31 09:05
Closing as won't do

**Closed by BorislavSabev** 2024-07-31 09:05 UTC
Labels: enhancement
